config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('doc/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path('', include('main_page_domer.urls')),
    path('users/', include('users.urls')),
    path('advertisement/', include('advertisement.urls')),
    path('api/v1/', include('api_domer.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_page_domer/urls.py
from django.urls import path

from main_page_domer.views import *

urlpatterns = [
    path('', get_main_page, name='home'),
    path('stores/', get_stores_page, name='stores'),
    path('stores/<slug:category_slug>/', get_stores_by_category, name='stores_by_category'),
    path('store/<slug:store_slug>/', get_store_by_title, name='store_by_title'),
    path('store/<slug:store_slug>/<slug:category_slug>/', get_store_by_title_and_category, name='store_by_title_and_category'),
    path('help/', get_help_page, name='help'),
]

users/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, reverse_lazy

from .views import logout_view, login_view, register_view, get_personal_account_page, get_incoming_page, \
    get_outgoing_page, get_sent_page, get_admin_message_page, add_store, get_my_store, edit_store, get_store_page, \
    delete_store, get_user_data_page, get_personal_account_inactive_adds_page, delete_or_archive_selected_ads

app_name = 'users'
urlpatterns = [
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('register/', register_view, name="register"),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name="base.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),

    path('reset_password_sent/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),

    path('reset_password_complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('personal_account/', get_personal_account_page, name='personal_account'),
    path('personal_account/delete_or_archive_ads/', delete_or_archive_selected_ads, name='delete_or_archive_ads'),
    path('personal_account/archived_adds/', get_personal_account_inactive_adds_page, name='inactive_adds'),
    path('user_data/', get_user_data_page, name='user_data'),
    path('incoming_messages/', get_incoming_page, name='incoming_messages'),
    path('outgoing_messages/', get_outgoing_page, name='outgoing_messages'),
    path('sent_messages/', get_sent_page, name='sent_messages'),
    path('admin_messages/', get_admin_message_page, name='admin_messages'),
    path('add_store/', add_store, name='add_store'),
    path('my_store/', get_my_store, name='my_store'),
    path('edit_store/<int:store_id>/', edit_store, name='edit_store'),
    path('delete_store/<int:store_id>/', delete_store, name='delete_store'),
    path('store/<slug:slug>/', get_store_page, name='store_page'),
]

main_page_domer/models.py
from django.db import models
from django.conf import settings
from advertisement.models import Advertisement


class Comment(models.Model):
    advertisement = models.ForeignKey(Advertisement, on_delete=models.CASCADE, verbose_name='Связь с объявлением')
    comment = models.TextField(verbose_name='Текст комментария')
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE, verbose_name='Автор')
    date_of_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    moderated = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.author


class Complaint(models.Model):
    reason = models.ForeignKey('ReasonOfComplaint', on_delete=models.CASCADE, verbose_name='Причина жалобы')
    text = models.TextField(verbose_name='Текст жалобы')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания жалобы')
    user = models.CharField(max_length=255, verbose_name='User')
    advertisement = models.ForeignKey(Advertisement, on_delete=models.CASCADE, verbose_name='Объявление')

    class Meta:
        verbose_name = 'Жалоба'
        verbose_name_plural = 'Жалобы'

    def __str__(self):
        return self.reason.reason


class ReasonOfComplaint(models.Model):
    reason = models.CharField('Причина жалобы', max_length=1000)

    class Meta:
        verbose_name = 'Причина жалобы'
        verbose_name_plural = 'Причины жалобы'

    def __str__(self):
        return self.reason


class PhotoPublication(models.Model):
    photo = models.ImageField(upload_to='images', verbose_name='Фото')
    publication = models.ForeignKey('Publication', on_delete=models.CASCADE, verbose_name='Публикация')

    class Meta:
        verbose_name = 'Фото публикации'
        verbose_name_plural = 'Фото публикаций'

    def __str__(self):
        return self.publication


class Publication(models.Model):
    category = models.CharField(max_length=255, verbose_name='Категория')
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, verbose_name='URL')
    description = models.TextField(verbose_name='Текст с описанием')
    video_link = models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')
    preview_image = models.ImageField(upload_to='images',
                                      verbose_name='Главная фотография')
    date_of_create = models.DateTimeField(auto_now_add=True,verbose_name='Дата создания')
    counter_views = models.IntegerField(default=0, verbose_name='Счетчик просмотров')
    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return self.title

main_page_domer/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from advertisement.models import Advertisement, Region, Category, Store
from advertisement.utils import get_region_variables, sorted_by, sorted_by_number, get_view_type, \
    sorted_by_date_or_price, variables_for_paginator, get_view_type_for_store


def get_main_page(request):
    advertisement_queryset = Advertisement.objects.filter(
        is_active=True, moderated=True).select_related(
        'category', 'region').order_by("-date_of_create")[:10]
    regions_queryset = Region.objects.filter(level=0)
    category_list = Category.objects.filter(level__lte=1)
    context = {
        "adver": advertisement_queryset,
        "category_list": category_list,
        "regions": regions_queryset,
    }
    return render(request, 'main.html', context)


def get_stores_page(request):
    region_filter, region_param, region_bread_crumbs = get_region_variables(request.GET.get('region'))
    category_list = Category.objects.filter(level__lte=1)
    store_queryset = Store.objects.filter(is_active=True, **region_filter).select_related('category', 'region')
    category_queryset = Category.objects.add_related_count(Category.objects.root_nodes(),
                                                           Store,
                                                           'category',
                                                           'store_counts',
                                                           cumulative=True,
                                                           extra_filters={"region__in": region_filter['region__in'],})
    paginator = Paginator(store_queryset, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "stores_found": store_queryset.count(),
        "category": category_queryset,
        "region_bread_crumbs": region_bread_crumbs,
        "region_param": region_param,
        "category_list": category_list,
        "page_obj": page_obj
    }
    return render(request, 'stores.html', context)


def get_stores_by_category(request, category_slug):
    region_filter, region_param, region_bread_crumbs = get_region_variables(request.GET.get('region'))
    category_queryset_all = Category.objects.all()
    category_list = Category.objects.filter(level__lte=1)
    category = get_object_or_404(category_queryset_all, slug=category_slug)
    category_queryset_an = Category.objects.add_related_count(category.get_descendants(),
                                                              Store,
                                                              'category',
                                                              'store_counts',
                                                              cumulative=True,
                                                              extra_filters={"region__in": region_filter['region__in']})
    # category_queryset = category_queryset_an.filter(parent_id=category.id)
    store_queryset = Store.objects.filter(Q(category__in=category_queryset_an) |
                                                          Q(category__slug=category.slug),
                                                          **region_filter,
                                                          is_active=True).select_related(
                                                          'category',
                                                          'region')
    paginator = Paginator(store_queryset, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "stores_found": store_queryset.count(),
        "category": category_queryset_an,
        "region_bread_crumbs": region_bread_crumbs,
        "region_param": region_param,
        "category_list": category_list,
        "page_obj": page_obj
    }
    return render(request, 'stores_by_category.html', context)


def get_store_by_title(request, store_slug):
    order_by = sorted_by(request.COOKIES.get('sorted_by'))
    sort_for_paginator = sorted_by_number(request.COOKIES.get('sort'))
    state_sort_by_date = request.COOKIES.get('date', 0)
    view_type, html = get_view_type_for_store(request.COOKIES)
    region_filter, region_param, region_bread_crumbs = get_region_variables(request.GET.get('region'))

    if request.GET.get('date') or request.GET.get('price'):
        state_sort_by_date, order_by = sorted_by_date_or_price(request.GET)
    if request.GET.get('sort'):
        sort_for_paginator = sorted_by_number(request.GET.get('sort'))
    if request.GET.get('view_type'):
        view_type, html = get_view_type_for_store(request.GET)

    store_page = Store.objects.get(slug=store_slug)
    oblast = Region.objects.get(id=store_page.region.parent_id)
    category_list = Category.objects.filter(level__lte=1)
    advertisement_queryset = Advertisement.objects.filter(store=store_page, is_active=True,
                                                          moderated=True, **region_filter).select_related(
                                                          'category',
                                                          'region').order_by(order_by)
    category_queryset = Category.objects.add_related_count(Category.objects.root_nodes(),
                                                           Advertisement,
                                                           'category',
                                                           'advertisement_counts',
                                                           cumulative=True,
                                                           extra_filters={"region__in": region_filter['region__in'],
                                                                          "category__advertisement__in": advertisement_queryset})

    page_obj = variables_for_paginator(advertisement_queryset,
                                       request.GET.get('page'),
                                       sort_for_paginator)

    context = {
        'store_page': store_page,
        'oblast': oblast,
        "category_list": category_list,
        "ads_found": advertisement_queryset.count(),
        "category": category_queryset,
        "region_bread_crumbs": region_bread_crumbs,
        "region_param": region_param,
        "page_obj": page_obj,
        'date': state_sort_by_date,
        'view_type': view_type,
    }
    response = render(request, html, context)
    response.set_cookie('sort', sort_for_paginator)
    response.set_cookie('date', state_sort_by_date)
    response.set_cookie('sorted_by', order_by)
    response.set_cookie('view_type', view_type)

    return response


def get_store_by_title_and_category(request, store_slug, category_slug):
    order_by = sorted_by(request.COOKIES.get('sorted_by'))
    sort_for_paginator = sorted_by_number(request.COOKIES.get('sort'))
    state_sort_by_date = request.COOKIES.get('date', 0)
    view_type, html = get_view_type_for_store(request.COOKIES)
    region_filter, region_param, region_bread_crumbs = get_region_variables(request.GET.get('region'))

    if request.GET.get('date') or request.GET.get('price'):
        state_sort_by_date, order_by = sorted_by_date_or_price(request.GET)
    if request.GET.get('sort'):
        sort_for_paginator = sorted_by_number(request.GET.get('sort'))
    if request.GET.get('view_type'):
        view_type, html = get_view_type_for_store(request.GET)

    store_page = Store.objects.get(slug=store_slug)
    oblast = Region.objects.get(id=store_page.region.parent_id)
    category_queryset_all = Category.objects.all()
    category_list = Category.objects.filter(level__lte=1)
    category = get_object_or_404(category_queryset_all, slug=category_slug)
    category_bread_crumbs = category.get_ancestors(ascending=False, include_self=True)
    category_queryset_an = Category.objects.add_related_count(category.get_descendants(),
                                                              Advertisement,
                                                              'category',
                                                              'advertisement_counts',
                                                              cumulative=True,
                                                              extra_filters={"region__in": region_filter['region__in'],})
    category_queryset = category_queryset_an.filter(parent_id=category.id)
    advertisement_queryset = Advertisement.objects.filter(Q(category__in=category_queryset_an) |
                                                          Q(category__slug=category.slug), store=store_page,
                                                          **region_filter,
                                                          is_active=True).select_related(
                                                          'category',
                                                          'region')

    page_obj = variables_for_paginator(advertisement_queryset,
                                       request.GET.get('page'),
                                       sort_for_paginator)

    context = {
        'store_page': store_page,
        'oblast': oblast,
        "category_list": category_list,
        "ads_found": advertisement_queryset.count(),
        "category": category_queryset,
        "category_bread_crumbs": category_bread_crumbs,
        "region_bread_crumbs": region_bread_crumbs,
        "region_param": region_param,
        'page_obj': page_obj,
        'date': state_sort_by_date,
        'view_type': view_type,
    }
    response = render(request, html, context)
    response.set_cookie('sort', sort_for_paginator)
    response.set_cookie('date', state_sort_by_date)
    response.set_cookie('sorted_by', order_by)
    response.set_cookie('view_type', view_type)

    return response


def get_help_page(request):

main_page_domer/templates/bany.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>srgdsrgsdr</h1>
</body>
</html>

main_page_domer/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <link rel="stylesheet" href="{% static 'css/null_for_templates.css' %}">
    <link rel="stylesheet" href="{% static 'css/main_page_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/stores.css' %}">
    <link rel="stylesheet" href="{% static 'css/add_edit_delete_store.css' %}">
    <link rel="stylesheet" href="{% static 'css/user_data.css' %}">
    {% block stylesheet %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/store_page.css' %}">

</head>
<body>
<div class="popup">
    <div class="login_form_popup">
        <form id="login_form" method="POST" class="login_form" action="">
            {% csrf_token %}
            <nav class="header_login_form_popup nav_popup">
                <img src="{% static 'img/logo.png' %}" alt="{% static 'img/logo.png' %}">
                <p>Вход</p>
            </nav>
            <p id="login_form_error"></p>
            {{ login_form }}
            <input type="button" id="form_login_button" value="Отправить">
        </form>
        <div class="forget_pass_and_register_buttons">
            <button class="forget_pass_button">Забыли пароль?</button>
            <button class="register_button">Регистрация</button>
        </div>
        <div class="closing_cross"></div>
    </div>
    <div class="register_form_popup">
        <form id="register_form" method="POST" class="register_form" action="">
            {% csrf_token %}
            <nav class="header_registration_form_popup nav_popup">
                <img src="{% static 'img/logo.png' %}" alt="{% static 'img/logo.png' %}">
                <p>Регистрация</p>
            </nav>
            <ul>
                <li style="display: flex;color:red" class="error_name_register"></li>
                <li style="display: flex;color:red" class="error_email_register"></li>
                <li style="display: flex;color:red" class="error_phone_register"></li>
                <li style="display: flex;color:red" class="error_pass_not_match_register"></li>
                <li style="display: flex;color:red" class="error_bad_password_register"></li>
            </ul>
            {{ register_form.as_p }}
            <input type="button" id="form_register_button" value="Регистрация"></input>
        </form>
        <button class="return_to_login_button">Вход</button>
        <div class="closing_cross"></div>
    </div>
    <div class="forget_pass_form_popup">
        <form id="forget_pass_form" action="{% url 'users:password_reset' %}" method="POST" class="forget_pass_form">
            {% csrf_token %}
            <nav class="header_registration_form_popup nav_popup">
                <img src="{% static 'img/logo.png' %}" alt="{% static 'img/logo.png' %}">
                <p>Восстановление пароля</p>
            </nav>
            {{ email_reset_form }}
            <button id="send_email_button">Отправить</button>
        </form>
        <button class="return_to_login_from_forget_button">Вход</button>
        <div class="closing_cross"></div>
    </div>
    <div class="nav_category_list_popup">
        {% for category in category_list %}
            {% if category.level == 0 %}
                {% if category.title == 'Транспорт' or category.title == 'Хобби и отдых' %}
                    <a href="" class="category_footer_item item_0">
                        {{ category.title }}
                    </a>
                {% else %}
                    <p></p>
                    <a href="" class="category_footer_item item_0">
                        {{ category.title }}
                    </a>
                {% endif %}
            {% else %}
                <a href="" class="category_footer_item item_1">
                    {{ category.title }}
                </a>
            {% endif %}
        {% endfor %}
        <div class="closing_cross"></div>
    </div>
</div>
<div class="wrapper">
    <div class="container">
        <header>
            <section class="header_up">
                <div class="header_up_wrapper">
                    <nav class="header_up_wrapper_navigate_info">
                        <ul>
                            <li>
                                <a href="{% url 'advertisement' %}" class="declarations">Объявления</a>
                            </li>
                            <li>
                                <a href="{% url 'stores' %}" class="shops">Магазины</a>
                            </li>
                            <li>
                                <a href="#" class="publications">Публикации</a>
                            </li>
                            <li>
                                <a href="{% url 'help' %}" class="help">Помощь</a>
                            </li>
                        </ul>
                        <div class='user_name'>
                            {% if user.is_authenticated %}
                                <a href="{% url 'users:logout' %}">Выход</a> |
                                <a href="{% url 'users:personal_account' %}">{{ user }}</a>
                            {% else %}
                                <p class="login_button">Вход и регистрация</p>
                            {% endif %}

                        </div>
                    </nav>
                </div>
                <div class="horizontal_line"></div>
            </section>
            <section class="header_down">
                <div class="header_down_category">
                    <div class="header_down_logo">
                        <a href="{% url 'home' %}">
                            <img src="{% static 'img/logo.png' %}" alt="{% static 'img/logo.png' %}">
                        </a>
                    </div>
                    <nav class="header_down_nav_category">
                        {% block nav_title %}
                            <div class="nav_category_title">
                                <p>
                                    { adaptive_navigation }
                                </p>
                            </div>
                        {% endblock %}
                        <div class="nav_category_list">
                            <a href="#">Авто</a>
                            <a href="#">Работа</a>
                            <a href="#">Недвижимость</a>
                            <button class="more_button">Ещё...</button>
                        </div>
                    </nav>
                    <nav class="header_down_get_ads">
                        <a href="{% url 'place_an_ad' %}" class="button_ads">
                            <img src="{% static 'img/button.png' %}" alt="{% static 'img/button.png' %}">
                        </a>
                    </nav>
                </div>
            </section>
        </header>
        {% block find %}
            <section class="search_table">
                <nav class="table_topics_search_location">
                    <select name="#" id="#" class="table_topics slct">
                        <option value="#">Все разделы</option>
                    </select>
                    <input type="text" placeholder="Поиск по тексту" class="table_search">
                    <select name="#" id="#" class="table_location slct">
                        <option value="#">Любое расположение</option>
                    </select>
                </nav>
                <div class="checkbox">
                    <div class="checkbox_list">
                        <div class="checkbox_input_label">
                            <input id="1" type="checkbox">
                            <label for="1" class="checkbox_label">Только в заголовках</label>
                        </div>
                        <div class="checkbox_input_label">
                            <input id="2" type="checkbox">
                            <label for="2" class="checkbox_label">С фото</label>
                        </div>
                        <div class="checkbox_input_label">
                            <input id="3" type="checkbox">
                            <label for="3" class="checkbox_label">С видео</label>
                        </div>
                    </div>
                    <div class="checkbox_button">
                        <input type="image" name="submit" src="{% static 'img/poisk.png' %}">
                    </div>
                </div>
            </section>
        {% endblock %}
        {% block filter %}

        {% endblock %}
        {% block content %}
        {% endblock %}
        {% block paginator %}
        {% endblock %}
        {% block prefooter %}
        {% endblock %}
        <footer>
            <div class="navigate_link">
                <div class="footer_link">
                    <a href="#">
                        <p>Подать объявление</p>
                    </a>
                </div>
                <div class="footer_link">
                    <a href="#">
                        <p>Объявления</p>
                    </a>
                </div>
                <div class="footer_link">
                    <a href="{% url 'stores' %}">
                        <p>Магазины</p>
                    </a>
                </div>
                <div class="footer_link">
                    <a href="{% url 'help' %}" class="help">Помощь</a>
                </div>
                <div class="footer_link">
                    <a href="#">
                        <p>Виджеты</p>
                    </a>
                </div>
                <div class="footer_link">
                    <a href="#">
                        Карта
                    </a>
                </div>
                <div class="footer_link">
                    <a href="#">
                        Обратная связь
                    </a>
                </div>
                <div class="footer_link">
                    <a href="#">
                        МОБИЛЬНАЯ ВЕРСИЯ
                    </a>
                </div>
            </div>
        </footer>
    </div>
</div>

<script src="{% static 'js/modals.js' %}"></script>
<script src="{% static 'js/auth.js' %}"></script>
{% block javascript %}
{% endblock %}

</body>
</html>

main_page_domer/templates/main.html
{% extends 'base.html' %}
{% load static %}
<title>Главная</title>

{% block nav_title %}
    <div class="nav_category_title">
        <p>
            Общебелорусская доска объявлений
        </p>
    </div>
{% endblock %}
{% block filter %}
    <section class="regions">
        <ul class="regions_list">
            {% for region in regions %}
                <li>
                    <a href="{% url 'advertisement' %}?region={{ region.id }}" class="minsk reg">{{ region.area|upper }}</a>
                </li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}
{% block content %}
    <main>
        <section>
            <div class="vip_cart_and_ads">
                <div class="vip_cart_list">
                    <a href="#" class="vip_cart">
                        <p class="vip_cart_header">VIP Объявление</p>
                    </a>
                    <a href="#" class="vip_cart">
                        <p class="vip_cart_header">VIP Объявление</p>
                    </a>
                </div>
                <div class="ads_wrapper">
                    <div class="last_ads_title">
                        Последние объявления
                    </div>

                    {% for cart in adver %}
                        <div class="ads_list">

                            <div class="ads">

                                <div class="ads_date_time">
                                    <ul>
                                        {% if cart.date_of_create.date == date_today %}
                                            <li>Сегодня</li>
                                        {% elif cart.date_of_create.date == date_yesterday %}
                                            <li>Вчера</li>
                                        {% else %}
                                            <li>{{ cart.date_of_create|date:"d b. Y" }}</li>
                                        {% endif %}
                                        <li>{{ cart.date_of_create|date:"H:i" }}</li>
                                    </ul>
                                </div>
                                <div class="ads_img">
                                    <img src="{{ cart.preview_image.url }}" alt="{{ cart.preview_image.url }}">
                                </div>
                                <div class="ads_description">
                                    <ul>
                                        <li>
                                            <a href="#" class="ads_description_title">
                                                {{ cart.title }}
                                            </a>
                                        </li>
                                        <li>
                                            {% if cart.price %}
                                                {{ cart.price }} руб.
                                            {% endif %}
                                        </li>
                                        <li>
                                            {{ cart.category }}
                                        </li>
                                        <li>
                                            {{ cart.bearer }}
                                        </li>
                                        <li>
                                            {{ cart.region }}
                                        </li>
                                    </ul>

                                </div>

                            </div>
                            <div class="line"></div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>

{% endblock %}