config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('doc/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path('', include('main_page_domer.urls')),
    path('users/', include('users.urls')),
    path('advertisement/', include('advertisement.urls')),
    path('api/v1/', include('api_domer.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, reverse_lazy

from .views import logout_view, login_view, register_view, get_personal_account_page, get_incoming_page, \
    get_outgoing_page, get_sent_page, get_admin_message_page, add_store, get_my_store, edit_store, get_store_page, \
    delete_store, get_user_data_page, get_personal_account_inactive_adds_page, delete_or_archive_selected_ads

app_name = 'users'
urlpatterns = [
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('register/', register_view, name="register"),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name="base.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),

    path('reset_password_sent/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")
         ),
         name='password_reset_confirm'),

    path('reset_password_complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('personal_account/', get_personal_account_page, name='personal_account'),
    path('personal_account/delete_or_archive_ads/', delete_or_archive_selected_ads, name='delete_or_archive_ads'),
    path('personal_account/archived_adds/', get_personal_account_inactive_adds_page, name='inactive_adds'),
    path('user_data/', get_user_data_page, name='user_data'),
    path('incoming_messages/', get_incoming_page, name='incoming_messages'),
    path('outgoing_messages/', get_outgoing_page, name='outgoing_messages'),
    path('sent_messages/', get_sent_page, name='sent_messages'),
    path('admin_messages/', get_admin_message_page, name='admin_messages'),
    path('add_store/', add_store, name='add_store'),
    path('my_store/', get_my_store, name='my_store'),
    path('edit_store/<int:store_id>/', edit_store, name='edit_store'),
    path('delete_store/<int:store_id>/', delete_store, name='delete_store'),
    path('store/<slug:slug>/', get_store_page, name='store_page'),
]

users/models.py
from django.contrib import admin
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField('Контактное лицо', max_length=255)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    phone_number = models.CharField('Номер телефона', max_length=15)
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    # avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    @admin.display
    def set_input(self):
        return format_html(
            "<input type='text'>"
        )

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

users/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import redirect, render

from advertisement.models import Region, Category, Advertisement, Store
from advertisement.forms import StoreForm
from .forms import LoginForm, RegisterForm, EditContactDataForm, ChangePasswordForm
from .models import User


def get_personal_account_page(request):
    """ Выводит все активные объявления пользователя в ЛК"""
    ads = Advertisement.objects.filter(author=request.user, is_active=True).select_related('category', 'region').all().order_by('-date_of_create')
    active_ads_quantity = ads.count()
    inactive_ads_quantity = Advertisement.objects.filter(author=request.user, is_active=False).count()
    category_list = Category.objects.filter(level__lte=1)
    paginator = Paginator(ads, 20)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "ads": ads,
        "active_ads_quantity": active_ads_quantity,
        "inactive_ads_quantity": inactive_ads_quantity,
        "category_list": category_list,
        "page_obj": page_obj
    }
    return render(request, 'personal_account/personal_account.html', context)


def get_personal_account_inactive_adds_page(request):
    """ Выводит все неактивные объявления пользователя в ЛК"""
    ads = Advertisement.objects.filter(author=request.user, is_active=False).select_related('category', 'region').all().order_by('-date_of_create')
    inactive_ads_quantity = ads.count()
    active_ads_quantity = Advertisement.objects.filter(author=request.user, is_active=True).count()
    category_list = Category.objects.filter(level__lte=1)

    paginator = Paginator(ads, 20)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "ads": ads,
        "inactive_ads_quantity": inactive_ads_quantity,
        "active_ads_quantity": active_ads_quantity,
        "category_list": category_list,
        "page_obj": page_obj
    }
    return render(request, 'personal_account/inactive_adds.html', context)


def delete_or_archive_selected_ads(request):
    if request.method == "POST":
        # Удаляет выбранные объявления из активных или архивных
        if 'delete_ads' in request.POST:
            selected_ads = request.POST.getlist('ads_checkbox')
            Advertisement.objects.filter(id__in=selected_ads).delete()
            messages.success(request, "Выбранные объявления удалены!")
            return redirect('users:personal_account')
        # Переводит выбранные объявления из активных в архивные
        if 'archive_ads' in request.POST:
            selected_ads = request.POST.getlist('ads_checkbox')
            Advertisement.objects.filter(id__in=selected_ads).update(is_active=False)
            messages.success(request, "Выбранные объявления перемещены в Архивные!")
            return redirect('users:personal_account')


@login_required
def get_user_data_page(request):
    """ Обрабатывает в личном кабинете две формы на изменение контактных данных и пароля пользователя """
    user = request.user
    edit_contact_data_form = EditContactDataForm(instance=user)
    change_pass_form = ChangePasswordForm()
    category_list = Category.objects.filter(level__lte=1)
    if request.method == "POST":
        # Изменяем контактные данные пользователя
        if 'edit_contact_data' in request.POST:
            edit_contact_data_form = EditContactDataForm(request.POST, instance=user)
            if edit_contact_data_form.is_valid():
                edit_contact_data_form.save()
                messages.success(request, "Контактные данные пользователя успешно изменены!")
                return redirect('users:user_data')
        # Изменяем пароль пользователя
        elif 'change_password' in request.POST:
            change_pass_form = ChangePasswordForm(request.POST, instance=user)
            if change_pass_form.is_valid():
                password = change_pass_form.cleaned_data.get("password")
                new_password = change_pass_form.cleaned_data.get("new_password")
                repeat_new_pass = change_pass_form.cleaned_data.get("repeat_new_pass")
                if password == user.password and password and new_password and repeat_new_pass:
                    user.set_password(new_password)
                    user.save()
                    update_session_auth_hash(request, user)
                    messages.success(request, "Пароль пользователя успешно изменён!")
                    return redirect('users:user_data')
    context = {'edit_contact_data_form': edit_contact_data_form,
               'change_pass_form': change_pass_form,
               'category_list': category_list
               }
    return render(request, 'personal_account/user_data.html', context)


def get_incoming_page(request):
    category_list = Category.objects.filter(level__lte=1)
    context = {
        "category_list": category_list,
    }
    return render(request, 'personal_account/incoming_messages.html', context)


def get_outgoing_page(request):
    category_list = Category.objects.filter(level__lte=1)
    context = {
        "category_list": category_list,
    }
    return render(request, 'personal_account/outgoing_messages.html', context)


def get_sent_page(request):
    category_list = Category.objects.filter(level__lte=1)
    context = {
        "category_list": category_list,
    }
    return render(request, 'personal_account/sent_messages.html', context)


def get_admin_message_page(request):
    category_list = Category.objects.filter(level__lte=1)
    context = {
        "category_list": category_list,
    }
    return render(request, 'personal_account/admin_message.html', context)


# Сохранение экземпляра нового магазина через форму
def add_store(request):
    if request.method == 'POST':
        new_store = StoreForm(request.POST, request.FILES)
        if new_store.is_valid():
            store = new_store.save(commit=False)
            store.user = request.user
            store.save()
            messages.success(request, f"Новый магазин {store} успешно создан!")
            return redirect('users:my_store')

        oblast = Region.objects.filter(type='Область')
        store_form = StoreForm(request.POST, request.FILES)
        store_form.errors.update(new_store.errors)
        category_list = Category.objects.filter(level__lte=1)
        context = {"oblast": oblast,
                   "store_form": store_form,
                   "category_list": category_list}
        return render(request, 'personal_account/add_store.html', context)

    oblast = Region.objects.filter(type='Область')
    store_form = StoreForm(initial={'contact_name': request.user.first_name, 'email': request.user.email,
                                    'phone_num': request.user.phone_number})
    category_list = Category.objects.filter(level__lte=1)

    context = {"oblast": oblast,
               "store_form": store_form,
               "category_list": category_list}
    return render(request, 'personal_account/add_store.html', context)


# Показывает в личном кабинете все магазины, которые создал пользователь
def get_my_store(request):
    stores = Store.objects.filter(user=request.user).order_by('id')
    category_list = Category.objects.filter(level__lte=1)
    oblast_list = []
    if stores.exists():
        context = {
            'stores': stores,
            'oblast_list': oblast_list,
            'category_list': category_list,
        }
    else:
        context = {}
    return render(request, 'personal_account/my_store.html', context)


# Открывает страницу выбранного в ЛК магазина
def get_store_page(request, slug):
    store_page = Store.objects.get(user=request.user, slug=slug)
    oblast = Region.objects.get(id=store_page.region.parent_id)
    category_list = Category.objects.filter(level__lte=1)
    context = {
        'store_page': store_page,
        'oblast': oblast,
        'category_list': category_list
    }
    return render(request, 'personal_account/store_page.html', context)


# Редактирование экземпляра магазина через форму
def edit_store(request, store_id):
    store = Store.objects.get(user=request.user, id=store_id)
    if request.method == 'POST':
        edit_selected_store = StoreForm(request.POST, request.FILES, instance=store)
        if edit_selected_store.is_valid():
            updated_store = edit_selected_store.save(commit=False)
            updated_store.user = request.user
            updated_store.save()
            messages.success(request, f"Магазин {store} успешно изменён!")
            return redirect('users:my_store')

    else:
        edit_selected_store = StoreForm(instance=store)

    oblast = Region.objects.filter(type='Область')
    selected_oblast = Region.objects.get(id=store.region.parent_id)
    categories = Category.objects.all()
    category_list = Category.objects.filter(level__lte=1)
    context = {
        'edit_store': edit_selected_store,
        'oblast': oblast,
        'selected_oblast': selected_oblast,
        'categories': categories,
        'selected_category': store.category.id if store.category else None,
        'store': store,
        'category_list': category_list
    }
    return render(request, 'personal_account/edit_store.html', context)


# Удаление экземпляра магазина
def delete_store(request, store_id):
    store = Store.objects.get(user=request.user, id=store_id)
    if request.method == "POST":
        store.delete()
        messages.success(request, f"Магазин {store} успешно удален!")
        return redirect('users:my_store')
    context = {'store': store}
    return render(request, 'personal_account/delete_store.html', context)


def logout_view(request):
    logout(request)

users/templates/personal_account/base_for_personal_account.html
<!DOCTYPE html>
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/null_for_templates.css' %}">
    <link rel="stylesheet" href="{% static 'css/personal_account_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/user_data.css' %}">
    <link rel="stylesheet" href="{% static 'css/messages.css' %}">
    <link rel="stylesheet" href="{% static 'css/add_edit_delete_store.css' %}">
    <link rel="stylesheet" href="{% static 'css/my_store.css' %}">
{% endblock %}
{% block popup %}
    <div class="popup_pa">
        <div class="nav_category_list_popup_pa">
            {% for category in category_list %}
                {% if category.level == 0 %}
                    {% if category.title == 'Транспорт' or category.title == 'Хобби и отдых' %}
                        <a href="" class="category_footer_item item_0">
                            {{ category.title }}
                        </a>
                    {% else %}
                        <p></p>
                        <a href="" class="category_footer_item item_0">
                            {{ category.title }}
                        </a>
                    {% endif %}
                {% else %}
                    <a href="" class="category_footer_item item_1">
                        {{ category.title }}
                    </a>
                {% endif %}
            {% endfor %}
            <div class="closing_cross_pa"></div>
        </div>
    </div>
{% endblock %}
<div class="wrapper">
    <div class="container">
        <header>
            {% block headerup %}
                <section class="header_up">
                    <div class="header_up_wrapper">
                        <nav class="header_up_wrapper_navigate_info">
                            <ul>
                                <li>
                                    <a href="{% url 'advertisement' %}" class="declarations">Объявления</a>
                                </li>
                                <li>
                                    <a href="{% url 'stores' %}" class="shops">Магазины</a>
                                </li>
                                <li>
                                    <a href="#" class="publications">Публикации</a>
                                </li>
                                <li>
                                    <a href="{% url 'help' %}" class="help">Помощь</a>
                                </li>
                            </ul>
                            <div class="user_name">
                                <a href="{% url 'users:logout' %}">Выход</a> | <a
                                    href="{% url 'users:personal_account' %}">{{ user }}</a>
                            </div>
                        </nav>
                    </div>
                    <div class="horizontal_line"></div>
                </section>
            {% endblock %}
            {% block headerdown %}
                <section class="header_down">
                    <div class="header_down_category">
                        <div class="header_down_logo">
                            <a href="{% url 'home' %}">
                                <img src="{% static 'img/logo.png' %}" alt="{% static 'img/logo.png' %}">
                            </a>
                        </div>
                        <nav class="header_down_nav_category">
                            {% block nav_title %}
                                <div class="nav_category_title">
                                    <p>
                                        { adaptive_navigation }
                                    </p>
                                </div>
                            {% endblock %}
                            <div class="nav_category_list">
                                <a href="#">Авто</a>
                                <a href="#">Работа</a>
                                <a href="#">Недвижимость</a>
                                <button class="more_button_pa">Ещё...</button>
                            </div>
                        </nav>
                        <nav class="header_down_get_ads">
                            <a href="#" class="button_ads">
                                <img src="{% static 'img/button.png' %}" alt="{% static 'img/button.png' %}">
                            </a>
                        </nav>
                    </div>
                </section>
            {% endblock %}
        </header>
        {% block user_search_table %}
            <main>
                <section class="search_table">
                    <nav class="table_topics_search_location">
                        <select name="#" id="#" class="table_topics slct">
                            <option value="#">Все разделы</option>
                        </select>
                        <input type="text" placeholder="Поиск по тексту" class="table_search">
                        <select name="#" id="#" class="table_location slct">
                            <option value="#">Любое расположение</option>
                        </select>
                    </nav>

                    <div class="search_checkbox_button">
                        <nav class="search_ads">
                            <input type="text" placeholder="№ объявления">
                        </nav>
                        <div class="checkbox_list">
                            <input id="1" type="checkbox">
                            <label for="1" class="checkbox_label">В заголовках</label>
                        </div>
                        <div class="checkbox_button">
                            <input type="image" name="submit" src="{% static 'img/poisk.png' %}">
                        </div>
                    </div>
                </section>
            </main>
        {% endblock %}
        {% block line %}
        <div class="line"></div>
        {% endblock %}
        {% block user_navigation %}
            <div class="body">
                <nav class="personal_account_navigation">
                    <ul>
                        <li class="wallet">
                            <p class="wallet_title">В Вашем кошельке</p>
                            <p class="wallet_amount"> 0,00 руб.</p>
                        </li>
                        <li>
                            <a href="{% url 'users:logout' %}" class="green_item">Выход</a>
                        </li>
                        <li>
                            <a href="{% url 'users:user_data' %}">Контактные данные</a>
                        </li>
                        <li>
                            <a href="{% url 'users:personal_account' %}">Мои объявления</a>
                        </li>
                        <li>
                            <a href="{% url 'users:add_store' %}" class="red_item">Добавить магазин</a>
                        </li>
                        <li>
                            <a href="{% url 'users:my_store' %}">Мои магазины</a>
                        </li>
                        <li>
                            <a href="{% url 'users:incoming_messages' %}">Входящие сообщения</a>
                        </li>
                        <li>
                            <a href="{% url 'users:outgoing_messages' %}">Исходящие сообщения</a>
                        </li>
                        <li>
                            <a href="{% url 'users:sent_messages' %}">Отправленные сообщения</a>
                        </li>
                        <li>
                            <a href="#">История платежей</a>
                        </li>
                        <li>
                            <a href="#" class="red_item">Пополнить кошелек</a>
                        </li>
                    </ul>
                </nav>
                {% block content %}
                {% endblock %}
            </div>
        {% endblock %}
    </div>
</div>
{% block javascript %}
    <script src="{% static 'js/modals_for_personal_account.js' %}"></script>
{% endblock %}
</html>

users/templates/personal_account/my_store.html
{% extends 'personal_account/base_for_personal_account.html' %}

{% load static %}

{% block nav_title %}
    <div class="nav_category_title">
        <p>
            Мои магазины
        </p>
    </div>
{% endblock %}

{% block user_search_table %}
{% endblock %}
{% block content %}
    <title>Мои магазины</title>
    <div class="personal_account_body">
        <div class="wrapper">
            <div class="container">
                <div class="body">
                    <div class="my_store">
                        {% if stores %}
                        {% for message in messages %}
                            {% if message.tags == 'success' %}
                                <div class="success-message">{{ message }}</div>
                                <script>
                                    setTimeout(function() {
                                        let successMessage = document.querySelector('.success-message');
                                        successMessage.style.display = 'none';
                                    }, 5000);
                                </script>
                            {% endif %}
                        {% endfor %}
                        {% for store in stores %}
                        <div class="store_block">
                            <div class="my_store_info">
                                <p class="store_title">{{ store.title }}</p>
                                <div class="change_store">
                                    <p><a href="{% url 'users:edit_store' store.id %}">Редактировать магазин</a></p>
                                    <p><a href="{% url 'users:delete_store' store.id %}">Удалить магазин</a></p>
                                </div>
                                <p class="store_date">
                                    Дата регистрации магазина: <span>{{ store.date_of_create|date:"j E Y" }}</span>
                                </p>
                                {% if store.is_active == False %}
                                    <p class="store_inactive">Магазин не активен</p>
                                    <p><a class="pay_store" href="#">Оплатить на год</a></p>
                                {% else %}
                                    <p class="store_date">
                                        Магазин активен до: <span>{{ store.date_of_deactivate|date:"j E Y" }} </span><span style="color: #008000">(Осталось {{ store.get_days_till_expiration }} дн.)</span>
                                    </p>
                                {% endif %}
                                <p><a href="{% url 'users:store_page' store.slug %}">Страница магазина на сайте</a></p>
                                <div class="my_store_table">
                                    <p class="table_name">Название</p>
                                    <p class="table_description">{{ store.title }}</p>
                                </div>
                                <div class="my_store_table">
                                    <p class="table_name">Раздел</p>
                                    <p class="table_description">{{ store.category.title }}</p>
                                </div>
                                <div class="my_store_table">
                                    <p class="table_name">Регион</p>
                                    <p class="table_description" id="{{store.region.parent_id}}">{{store.region.parent}}</p>
                                </div>
                                <div class="my_store_table">
                                    <p class="table_name">Город / район</p>
                                    <p class="table_description">{{ store.region.area }}</p>
                                </div>
                                <div class="my_store_table">
                                    <p class="table_name">Описание</p>
                                    <p class="table_description">{{ store.description }}</p>
                                </div>
                                <div class="my_store_table">
                                    <p class="table_name">Сайт магазина</p>
                                    {% if store.url == None %}
                                        <p class="table_description"><a href="{{ store.url }}"></a></p>
                                    {% else %}
                                        <p class="table_description"><a href="{{ store.url }}">{{ store.url }}</a></p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="my_store_img">
                                <img src="{{ store.logo_image.url }}" alt="{{ store.logo_image.url }}">
                            </div>
                        </div>
                        <div class="thin_line" style="margin-bottom: 10px"></div>
                        {% endfor %}
                        {% else %}
                            <div class="my_store_info">
                                {% for message in messages %}
                                    {% if message.tags == 'success' %}
                                        <div class="success-message">{{ message }}</div>
                                        <script>
                                                setTimeout(function() {
                                                    let successMessage = document.querySelector('.success-message');
                                                    successMessage.style.display = 'none';
                                                    }, 5000);
                                        </script>
                                        {% endif %}
                                {% endfor %}
                                <p class="store_title">У Вас нет созданных магазинов</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}